### ISSUE TITLE
Did you know that your container was used by someone else to make a virus？

### ISSUE THREAD

**Issue by 91wangmeng** [kannix/monero-miner#4]
Did you know that your container was used by someone else to make a virus？

**Comment by kannix** [comment]
No 😞 Do you have any more information on this or an idea if there is anything I could do about it?

**Comment by fuuqiu** [comment]
Currently being mounted to many servers for mining, very hurt

**Comment by kannix** [comment]
If someone can give me more information on this we could try to find a solution.. but for now I will close this. If someone is able to run unwanted docker containers in you infrastructure you should focus on how that could happen. This is a big indicator for at least a misconfiguration of your systems.

**Comment by fuuqiu** [comment]
Scanned remote deployment mining program to run in the docker environment, not ssl authentication can be avoided.

**Comment by kannix** [comment]
I am sorry but could you try to rephrase your comment? I don't understand it...

**Comment by fuuqiu** [comment]
The server opened the remote deployment, but did not open the ssl check, causing the hacker to scan.
